<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
Schema::create('teams',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('organization_id')->index();$t->string('name');$t->timestamps();$t->foreign('organization_id')->references('id')->on('organizations')->cascadeOnDelete();});
Schema::create('incidents',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('organization_id')->index();$t->unsignedBigInteger('incident_number');$t->string('title');$t->text('description')->nullable();$t->string('severity')->index();$t->string('status')->index();$t->foreignId('commander_user_id')->nullable();$t->unsignedBigInteger('version')->default(1);$t->unsignedBigInteger('last_sequence')->default(0);$t->timestampTz('started_at');$t->timestampTz('mitigated_at')->nullable();$t->timestampTz('resolved_at')->nullable();$t->timestamps();$t->unique(['organization_id','incident_number']);$t->foreign('organization_id')->references('id')->on('organizations')->cascadeOnDelete();$t->foreign('commander_user_id')->references('id')->on('users')->nullOnDelete();});
Schema::create('incident_participants',function(Blueprint $t){$t->uuid('incident_id');$t->foreignId('user_id');$t->string('role')->default('responder');$t->timestampTz('joined_at');$t->primary(['incident_id','user_id']);$t->foreign('incident_id')->references('id')->on('incidents')->cascadeOnDelete();$t->foreign('user_id')->references('id')->on('users')->cascadeOnDelete();});
Schema::create('incident_events',function(Blueprint $t){$t->bigIncrements('id');$t->uuid('incident_id')->index();$t->unsignedBigInteger('sequence');$t->string('event_type')->index();$t->foreignId('actor_user_id')->nullable();$t->jsonb('payload_json');$t->timestampTz('occurred_at');$t->uuid('client_command_id')->nullable();$t->unique(['incident_id','sequence']);$t->unique(['incident_id','client_command_id']);$t->foreign('incident_id')->references('id')->on('incidents')->cascadeOnDelete();$t->foreign('actor_user_id')->references('id')->on('users')->nullOnDelete();});
Schema::create('comments',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('incident_id')->index();$t->foreignId('user_id');$t->text('body');$t->unsignedBigInteger('version')->default(1);$t->timestampTz('edited_at')->nullable();$t->timestamps();$t->foreign('incident_id')->references('id')->on('incidents')->cascadeOnDelete();$t->foreign('user_id')->references('id')->on('users')->cascadeOnDelete();});
Schema::create('action_items',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('incident_id')->index();$t->string('title');$t->foreignId('assignee_user_id')->nullable();$t->string('status')->default('open');$t->unsignedBigInteger('version')->default(1);$t->timestampTz('due_at')->nullable();$t->timestamps();$t->foreign('incident_id')->references('id')->on('incidents')->cascadeOnDelete();$t->foreign('assignee_user_id')->references('id')->on('users')->nullOnDelete();});
Schema::create('outbox_messages',function(Blueprint $t){$t->uuid('id')->primary();$t->string('aggregate_type');$t->uuid('aggregate_id')->index();$t->string('event_type');$t->jsonb('payload_json');$t->unsignedInteger('attempts')->default(0);$t->timestampTz('available_at')->index();$t->timestampTz('published_at')->nullable()->index();$t->text('last_error')->nullable();$t->timestamps();});
}public function down():void{Schema::dropIfExists('outbox_messages');Schema::dropIfExists('action_items');Schema::dropIfExists('comments');Schema::dropIfExists('incident_events');Schema::dropIfExists('incident_participants');Schema::dropIfExists('incidents');Schema::dropIfExists('teams');}};
