import WebSocket from 'ws';
import { randomUUID } from 'node:crypto';

const wsUrl=process.env.REVERB_WS_URL||'ws://127.0.0.1:8080/app/local?protocol=7&client=js&version=8.4.0&flash=false';
const api=(process.env.PULSE_BASE_URL||'http://127.0.0.1:8000').replace(/\/$/,'');
const token=process.env.PULSE_TOKEN; const incident=process.env.INCIDENT_ID;
const clients=Number(process.env.CLIENTS||50); const burst=Number(process.env.EVENTS||100); const duration=Number(process.env.DURATION_SECONDS||20);
if(!token||!incident)throw new Error('PULSE_TOKEN and INCIDENT_ID are required for an authenticated incident-room load test');
let opened=0,subscribed=0,errors=0,received=0; const latencies=[]; const sockets=[];

async function auth(socketId){const body=new URLSearchParams({socket_id:socketId,channel_name:`presence-incidents.${incident}`});const r=await fetch(`${api}/api/broadcasting/auth`,{method:'POST',headers:{Authorization:`Bearer ${token}`,Accept:'application/json','Content-Type':'application/x-www-form-urlencoded'},body});if(!r.ok)throw new Error(`broadcast auth ${r.status}`);return r.json()}
function connect(){return new Promise((resolve,reject)=>{const ws=new WebSocket(wsUrl);sockets.push(ws);let settled=false;ws.on('open',()=>opened++);ws.on('message',async raw=>{try{const msg=JSON.parse(raw.toString());if(msg.event==='pusher:connection_established'){const d=JSON.parse(msg.data);const a=await auth(d.socket_id);ws.send(JSON.stringify({event:'pusher:subscribe',data:{channel:`presence-incidents.${incident}`,auth:a.auth,channel_data:a.channel_data}}));}else if(msg.event==='pusher_internal:subscription_succeeded'){subscribed++;if(!settled){settled=true;resolve(ws)}}else if(msg.event==='incident.event'){const d=typeof msg.data==='string'?JSON.parse(msg.data):msg.data;received++;if(d.occurred_at){const ms=Date.now()-Date.parse(d.occurred_at);if(Number.isFinite(ms)&&ms>=0)latencies.push(ms)}}}catch(e){errors++}});ws.on('error',e=>{errors++;if(!settled){settled=true;reject(e)}});});}
async function comment(i){const r=await fetch(`${api}/api/incidents/${incident}/comments`,{method:'POST',headers:{Authorization:`Bearer ${token}`,Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify({body:`socket-load-${i}`,client_command_id:randomUUID()})});if(!r.ok)throw new Error(`comment ${r.status}: ${await r.text()}`)}
const start=Date.now();await Promise.all(Array.from({length:clients},()=>connect()));const burstStarted=Date.now();await Promise.all(Array.from({length:burst},(_,i)=>comment(i)));await new Promise(r=>setTimeout(r,Math.max(1000,duration*1000)));for(const s of sockets)s.close();latencies.sort((a,b)=>a-b);const q=p=>latencies.length?latencies[Math.floor((latencies.length-1)*p)]:null;console.log(JSON.stringify({clients,opened,subscribed,events_sent:burst,event_deliveries_received:received,expected_event_deliveries:clients*burst,errors,setup_ms:burstStarted-start,broadcast_latency_ms:{p50:q(.5),p95:q(.95),max:latencies.at(-1)||null}},null,2));process.exit(errors?1:0);
